.PHONY: clean All

All:
	@echo "----------Building project:[ Matthews_Adam_GCD - Debug ]----------"
	@cd "Matthews_Adam_GCD" && "$(MAKE)" -f  "Matthews_Adam_GCD.mk"
clean:
	@echo "----------Cleaning project:[ Matthews_Adam_GCD - Debug ]----------"
	@cd "Matthews_Adam_GCD" && "$(MAKE)" -f  "Matthews_Adam_GCD.mk" clean
